server {
    listen 80;
    server_name lukin.me;
    server_name www.lukin.me;

    location / {
        return 301 https://lukin.me$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name www.lukin.me;

    ssl_certificate /etc/letsencrypt/live/lukin.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lukin.me/privkey.pem;

    location / {
        return 301 https://lukin.me$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name lukin.me;

    charset utf-8;
    root /srv/http/lukin.me/public;

    ssl_certificate /etc/letsencrypt/live/lukin.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lukin.me/privkey.pem;

    location = /robots.txt {
        log_not_found off;
        access_log off;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location /photopills/ {
        auth_basic "Restricted Area";
        auth_basic_user_file /etc/nginx/passwords/lukin-blog.conf;

        try_files $uri $uri/ =404;
    }
}
